GOOGLE_CLIENT_ID     = "878896184507-km46mjk3knsnlq12n1pav8bu5ktkn5qi.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI         = "http://localhost:8501"
